name    'puppet-redis'
version '0.0.1'
source 'http://github.com/mchesler/puppet-redis'
author 'Matt Chesler'
license 'Apache License Version 2.0'
summary 'Puppet Redis management module'
description 'This module can be used for basic redis Management'
project_page 'http://github.com/mchesler/puppet-redis'
